### ISSUE TITLE
手機瀏覽網頁版面遭精

### ISSUE THREAD

**Issue by Catossun** [macs1207/HowFun-blessing-generator#3]
如下圖：
![Screenshot_20200603-115607](https://user-images.githubusercontent.com/17540683/83594306-7b8e8480-a591-11ea-9a4c-9434bbc09bdc.png)

**Comment by macs1207** [comment]
Hi @Catossun 
目前我們正在處理這個問題 Thanks.

**Comment by macs1207** [comment]
Fixed in 3a2895e
