### ISSUE TITLE
Can I generate a video via http get parameter?

### ISSUE THREAD

**Issue by vn7n24fzkq** [macs1207/HowFun-blessing-generator#7]
As title.
We can avoid to generate duplicate video on server disk also ,if use the parameter as video id.
https://github.com/macs1207/HowFun-blessing-generator/blob/dd33195d55dc0b706cc61b059554aba3ff9abd5b/server.py#L67

**Comment by macs1207** [comment]
@vn7n24fzkq Should I comment in English? XD

Thus, the get param will become:
```json
{
    "text": "some text...",
    "videoId": "just id..."
}
```

Right?

**Comment by vn7n24fzkq** [comment]
中文也行😄
https://github.com/macs1207/HowFun-blessing-generator/blob/dd33195d55dc0b706cc61b059554aba3ff9abd5b/utils/video_process.py#L34
我輸入相同的text ,是否能產生相同的id, 目前的 id 看起來是UUID.

簡單的想法是:
 前端 input : 你好 -> 前端把 "你好" 轉成 base64 發送請求 http://howfun.macs1207.info/video?text=5L2g5aW9
 -> 後端解析 text param: 5L2g5aW9 ->產生 "你好" 影片

可以用在避免在伺服器上產生重複的檔案，或是未來實作快取清除過期影片時也可以從舊的URL取得影片
